import PyPDF2 as pd
import time

starttime = time.time() 
##filename = input('Path to the file: ')
file = open("/Users/vanshbafna/Desktop/module5/C223/Brute_Encrypted.pdf",'rb')
pdfReader = pd.PdfFileReader(file)

tried = 0

if not pdfReader.isEncrypted:
    print('The file is not password protected! You can successfully open it!')
else:
    wordListFile = open("/Users/vanshbafna/Desktop/module5/C223/wordlist123.txt")
    body = wordListFile.read().lower()
    words = body.split('\n')

    for i in range(len(words)):
        word = words[i]
        print("Trying To Decode Password By:{}".format(word))
        result = pdfReader.decrypt(word)
        endtime = time.time() 
        if result == 1:
            duration = endtime - starttime
            print("__xxxxxxxxxxxxxxxx___.\n _gxXXXXXXXXXXXXXXXXXXXXXXXX!x_\n __x!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!x_\n ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx_\n ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!_\n _!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.\n gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs\n ,!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.\n g!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n iXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx\n !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx\n ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx\n !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXi\n dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXf~~~VXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvvvvXXXXXXXXXXXXXX!\n !XXXXXXXXXXXXXXXf`       'XXXXXXXXXXXXXXXXXXXXXf`          '~XXXXXXXXXXP\n vXXXXXXXXXXXX!            !XXXXXXXXXXXXXXXXXX!              !XXXXXXXXX\n XXXXXXXXXXv`              'VXXXXXXXXXXXXXXX                !XXXXXXXX!\n !XXXXXXXXX.                 YXXXXXXXXXXXXX!                XXXXXXXXX\n XXXXXXXXX!                 ,XXXXXXXXXXXXXX                VXXXXXXX!\n 'XXXXXXXX!                ,!XXXX ~~XXXXXXX               iXXXXXX~\n 'XXXXXXXX               ,XXXXXX   XXXXXXXX!             xXXXXXX!\n !XXXXXXX!xxxxxxs______xXXXXXXX   'YXXXXXX!          ,xXXXXXXXX\n YXXXXXXXXXXXXXXXXXXXXXXXXXXX`    VXXXXXXX!s. __gxx!XXXXXXXXXP\n XXXXXXXXXXXXXXXXXXXXXXXXXX!      'XXXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXXXP        'YXXXXXXXXXXXXXXXXXXXXXXX!\n XXXXXXXXXXXXXXXXXXXXXXXX!     i    !XXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXX!     XX   !XXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXx_   iXX_,_dXXXXXXXXXXXXXXXXXXXXXXXX\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXP\n XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n ~vXvvvvXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf\n 'VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvv~\n 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~\n _    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`\n -XX!  !XXXXXXX~XXXXXXXXXXXXXXXXXXXXXX~   Xxi\n YXX  '~ XXXXX XXXXXXXXXXXXXXXXXXXX`     iXX`\n !XX!    !XXX` XXXXXXXXXXXXXXXXXXXX      !XX\n !XXX    '~Vf  YXXXXXXXXXXXXXP YXXX     !XXX\n !XXX  ,_      !XXP YXXXfXXXX!  XXX     XXXV\n !XXX !XX           'XXP 'YXX!       ,.!XXX!\n !XXXi!XP  XX.                  ,_  !XXXXXX!\n iXXXx X!  XX! !Xx.  ,.     xs.,XXi !XXXXXXf\n XXXXXXXXXXXXXXXXX! _!XXx  dXXXXXXX.iXXXXXX\n VXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXX!\n YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXV\n 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!\n 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf\n VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf\n VXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`\n ~vXXXXXXXXXXXXXXXXXXXXXXXf`\n ~vXXXXXXXXXXXXXXXXv~\n '~VvXXXXXXXV~~\n ~~\n \n")

            print('Your password decoded in'+str(duration)+' seconds')
            print("sucess the password is: " + word)
            break

        elif result == 0:
            tried += 1
            print("password tried: " + str(tried))
            continue
print("┈┈┈/▔▔▔▔╲\n┈┈┃┈▇┈┈▇┈┃\n╭╮┣━━━━━━┫╭╮\n┃┃┃┈┈┈┈┈┈┃┃┃\n╰╯┃┈┈┈┈┈┈┃╰╯\n┈┈╰┓┏━━┓┏╯\n┈┈┈╰╯┈┈╰╯")







